<!--FALTA ARREGLAR EDITAR DEPENDENCIA-->


<script src="http://maps.google.com/maps/api/js?libraries=drawing,places&key=AIzaSyDqDmTRIkqt3poS8eshH_Vro-u7bkXiH0s" type="text/javascript"></script>

<?php 
	$dependencias = $this->dependencias;
?>



<div class="container">
	<h1>Administración de dependencias</h1><br><br>

	<button class="btn btn-success" onclick="nuevaArea()" id="btn_nuevaDependencia">Nueva dependencia</button>
</div>
<br>


<div class="panel panel-default">
<div class="panel-heading">Dependencias</div>
<div class="panel-body">
<div class="table-responsive">
<table class="table table-striped text-center" id="dependencias">
	<thead>
		<tr>
			<th>Detalle</th>
			<th>Ver área válida</th>
			<th>Eliminar área</th>
		</tr>
	</thead>
	<tbody>
		<?php //Llena los campos de la tabla
			for($i = 0; $i < count($dependencias); $i++){ ?>
		<tr>
			<td><?php echo $dependencias[$i]['detalle'] ?></td>	
			<td><button class="btn btn-success" onclick="verArea('<?php echo $dependencias[$i]['area']?>','<?php echo $dependencias[$i]['id'] ?>','<?php echo $dependencias[$i]['detalle'] ?>')"><i class="fa fa-location-arrow" aria-hidden="true"></i></button></td>
			<td><button class="btn btn-danger" onclick="eliminarArea('<?php echo $dependencias[$i]['id']?>')"><i class="fa fa-trash" aria-hidden="true"></i></button></td>

		</tr>
		<?php } ?>
	</tbody>
</table>
</div>
</div>
</div>





<script src="<?php echo $this->baseUrl(); ?>/plugins/dataTables-1.10.11/datatables.min.js"></script>
<script type="text/javascript">
	function verArea(area, id, detalle){
		$.ajax({
            url: BASE_URL + "/index.php/index/modal-ver-area",
            dataType: 'html',
            type: "POST",
            data: {area: area, 
            id: id,
            detalle: detalle}
        }).done(function(response) {
      		$("#verArea").html(response);
      		$("#modalVerArea").modal();
  		});
	}


	function eliminarArea(id){
		conf = confirm("¿Desea borrar el area seleccionada?");
		if (conf){
			esperaON();
			$.ajax({
				url: BASE_URL + "/index.php/index/eliminar-area",
	            dataType: 'json',
	            type: "POST",
	            data: { 
	            	id: id
	     	    }
			}).done(function(response){
				console.log(response);
				alert(response.mensaje);
				if (response.estado == 'OK')
					location = BASE_URL + "/index.php/index/dependencias";
				else{
					esperaOFF;
				}
			})
		}
	}

	
//NO FUNCIONAAA

	function guardarArea(){
	    $("#imp_desc").css('border-color','');
		
		if ($("#imp_desc").val() == ""){
			alert("Debe ingresar nombre de localidad");
			return;
		}else if($("#wkt").val() == ""){
			alert("faltan datos");
			return;
		}	

		comp = confirm("¿Desea guardar los cambios?");

		if (comp) {
			esperaON();
	      	$.ajax({
		        url: BASE_URL + "/index.php/index/editar-dependencia",
	        	dataType: 'json',
	        	type: "POST",
	        	data: { 
	            	id:           $("#imp_id").val(),
	            	descripcion:  $("#imp_desc").val(), 
	            	descripcion_old:  $("#imp_desc_old").val(), 
	            	coord:   $("#wkt").val(),
	            	coord_old:   $("#wkt_old").val()
	        	}
	      	}).done(function(response) {
	            console.log(response);
	            alert(response.mensaje);
	            if(response.estado == "OK")
	        		location = BASE_URL + "/index.php/index/dependencias";
	        	else if(response.estado == "NO")
	        		$("#imp_desc").css('border-color','red');
	        	esperaOFF();
	            
		    });
	    } 
	}
	function nuevaArea(){
		$.ajax({
	            url: BASE_URL + "/index.php/index/modal-nueva-area",
	            dataType: 'html',
	            type: "POST",
	            data: {

	            }
	        }).done(function(response) {
				$("#agregarArea").html(response);
				$("#modalAgregarArea").modal();
		});
	}

	function crearArea(){
		
		if($('textarea#wkt').val() == ""){
			alert("No ha marcado una posicion");
		}
		else if($('#imp_desc').val() == ""){
			alert("Debe ingresar una descripcion del lugar");
		}
		else{
			esperaON();
			$.ajax({
				url: BASE_URL + "/index.php/index/crear-nueva-area",
				dataType: 'json',
	            type: "POST",
	            data: {
	            	desc: $('#imp_desc').val(),
	            	area: $('textarea#wkt').val()
	            }
			}).done(function(response){
				console.log(response);
				alert(response.mensaje);
				if(response.estado == "OK"){
					location = BASE_URL + "/index.php/index/dependencias";
				}
				else{
					esperaOFF();
				}
			});
		}
	}
</script>





<!--Modal para ver area-->
<div class="modal fade" id="modalVerArea" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Area </h3>
      </div>
      <div class="modal-body">
      
        <div id="verArea">
          
        </div>
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="guardarArea();">Guardar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<!--Modal para agregar area-->
<div class="modal fade" id="modalAgregarArea" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Crear área </h3>
      </div>
      <div class="modal-body">
      
        <div id="agregarArea">
          
        </div>
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" onclick="crearArea();">Guardar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
