<div class="card card-container">
    
    <img src="img/logo-entel-big.png" alt="" id="profile-img" class="profile-img-card">
    
    <p id="profile-name" class="profile-name-card">
        <i class="brackets">&#91;</i>
        &nbsp;Subgerencia de <strong>Operaciones</strong>&nbsp;
        <i class="brackets">&#93;</i>
    </p>
    
    <form id="form-login" class="form-signin">
        <!-- En caso de error agregar clase has-error -->
        <div class="form-group">
            <input type="text" id="username" name="username" class="form-control" placeholder="Nombre de Usuario" required autofocus>
        </div>
        
        <div class="form-group">
            <input type="password" id="clave" name="clave" class="form-control" maxlength="10" placeholder="Password" required>
        </div>

        <input id="btn-submit-login" class="btn btn-lg btn-primary btn-block btn-signin" value="Ingresar" type="submit">
    </form>

    <a href="#" class="forgot-password">&iquest;Olvid&oacute; su contraseña&quest;</a>
</div><!-- /Card Container -->