<head>
<style type="text/css" media="print">
	.hide{
		display: none;
	}
</style>
<style type="text/css" media="all">

body{
	font-family: sans-serif;
}
table {
  border-collapse: separate;
  border-spacing: 0;
  margin-left:auto; 
  margin-right:auto;
  font-size: 12px;
}

th {
  font-weight: bold;
  border: 1px solid #cecfd5;
  width: 180px;

}

td {
  border-bottom: 1px solid #cecfd5;
  border-right: 1px solid #cecfd5;
  border-left: 1px solid #cecfd5;
  border-top: 1px solid #cecfd5;
  text-align: center;
  padding: 5px 15px;
  
}

.sinBorde{
	border: 0px;
	height: 150px;
	text-align: center;
	font-size: 20px;

}
h3{
	margin-top: -50px;
	text-align: center
}
</style>
</head>
<body>
<a class="hide" href="<?php echo $this->baseUrl(); ?>/index.php/index/ver-horas-total">VOLVER</a>

<br><br><br>

<script src="<?php echo $this->baseUrl(); ?>/plugins/jQuery/jQuery-2.1.4.min.js"></script>

<?php 
	$rs = $this->infoHoraUsuarios;
	$fecha = $this->fecha;
	$periodo  = array(
    					1 => "Enero" ,
    					2 => "Febrero" ,
    					3 => "Marzo" ,
    					4 => "Abril" ,
    					5 => "Mayo" ,
    					6 => "Junio" ,
    					7 => "Julio" ,
    					8 => "Agosto" ,
    					9 => "Septiembre" ,
    					10 => "Octubre" ,
    					11 => "Noviembre" ,
    					12 => "Diciembre" 
    				);

	$fecha = explode("-", $fecha);

	
	function convertToHoursMins($time, $format = '%02d:%02d') {
	    if ($time < 1) {
	        return;
	    }
	    $hours = floor($time / 60);
	    $minutes = ($time % 60);
	    return sprintf($format, $hours, $minutes);
	}
?>
<h3>Periodo <?php echo $periodo[(int)$fecha[1]]." del " . $fecha[0]; ?></h3>
<label>Nombre: <?php echo $rs[0]['nombre'] ?></label><br>
<label style="float: right;"> Fecha: <?php echo date("d-m-Y"); ?></label>
<label>RUT: <?php echo $rs[0]['Rut'] ?></label>


<br><br>
<table>
<thead>
	<tr>
		<th>Fecha</th>
		<th>Hora de ingreso</th>
		<th>Hora de salida</th>
		<th>Horas trabajadas</th>
<!--
		<th>Horas de trabajo por día</th>
		<th>Diferencia</th>
-->
	</tr>
</thead>
<tbody>
<?php 
	

$hTotalPeriodo = 0;
$mTotalPeriodo = 0;

$hTotal = 0;
$mTotal = 0;

$hTotalDiferencia = 0;
$mTotalDiferencia = 0;

for ($i=0; $i < count($rs); $i++) {  
	if (count($rs[0]['fecha']) ){
		
?>
	<tr>


<!--fecha de registro-->
	<td><?php echo $rs[$i]['fecha']; ?></td>
<!--hora de ingreso-->
	<td><?php echo $rs[$i]['ingreso'] ?></td>
<!--hora de salida-->
	<td> <?php 
	 		if (is_null($rs[$i]['salida']))
	 			echo "18:00 *";
	 		else
	 			echo $rs[$i]['salida'] ?>
	 		
	</td>
<!--Horas trabajadas ese dia-->
	<td>
		<?php 

	 			$ingreso = new DateTime($rs[$i]['ingreso']);
	 			$salida = new DateTime();

	 			//si no marca salida, automaticamente coloca 18:00 hrs
	 			if(is_null($rs[$i]['salida'])){
	 				$salida = new DateTime('18:00');
	 			}

	 			else{
	 				$salida = new DateTime(	$rs[$i]['salida']);
	 			}
	 			$ingreso->format("H:i:s");
	 			$salida->format("H:i:s");
	 			$diferencia = $salida->diff($ingreso);

	 //horas trabajadas salida - ingreso
				echo $diferencia->format('%H:%I');
				
	//se suman horas y minutos trabajadas de cada dia
				$hTotalPeriodo += $diferencia->format('%H');
				$mTotalPeriodo += $diferencia->format('%I');
	 		?>

	</td>

<!--
	<td>
		<?php 
	 		
	 		$hora = new DateTime($rs[$i]['horasDiarias']);

	 		echo $hora->format('H:i');
	 		$hTotal += $hora->format('H');
	 		$mTotal += $hora->format('i');
	 //suma de horas requeridas por dia
	 	?>

	</td>
	<td>
		<?php 
	 			//horas de diferencia trabajadas con respecto a horas que se deben trabajar
	 			//horas trabajadas en el dia - reales
	 			$diferencia2 = new DateTime($diferencia->format('%H:%I:%S'));
	 			$difCalculada = $diferencia2-> diff($hora);
	 			if($diferencia2 < $hora){

	 				//calcula la diferencia de hora total 
	 				echo "-";
	 				$hTotalDiferencia -= $difCalculada->format('%H');
	 				$mTotalDiferencia -= $difCalculada->format('%I');

	 			}
	 			else{
	 				$hTotalDiferencia += $difCalculada->format('%H');
	 				$mTotalDiferencia += $difCalculada->format('%I');
	 			}
	 			echo $difCalculada->format('%H:%I');	

	 		?>

	</td>
-->
	</tr>
<?php } }
//los minutos mayores a 60, pasan a las horas.
		$minToHour = explode(":",convertToHoursMins($mTotalPeriodo, '%02d:%02d'));
		$hTotalPeriodo += $minToHour[0];
		if (isset($minToHour[1]))
			$mTotalPeriodo = $minToHour[1];

		$minToHour = explode(":",convertToHoursMins($mTotal, '%02d:%02d'));
		$hTotal += $minToHour[0];
		if (isset($minToHour[1]))
			$mTotal = $minToHour[1];
?>

	<tr>
		<td colspan="3" style="text-align: left"><strong>TOTAL</strong></td>
		
		<td><?php echo sprintf('%02d:%02d',$hTotalPeriodo, $mTotalPeriodo);  ?></td>
<!--
		<td><?php echo sprintf('%02d:%02d',$hTotal, $mTotal); ?></td>
		<td>
			<?php 
			$minToHour = explode(":",convertToHoursMins(abs($mTotalDiferencia), '%02d:%02d'));

			if ($mTotalDiferencia>0){
				$hTotalDiferencia += $minToHour[0];
			}else{
				$hTotalDiferencia -= $minToHour[0];
			}
			if (isset($minToHour[1]))
				$mTotalDiferencia = $minToHour[1];

			echo sprintf('%02d:%02d',$hTotalDiferencia,$mTotalDiferencia); 
		?>
		
		</td>
-->
	</tr>
	
	<tr >
	<td class="sinBorde"></td><td class="sinBorde"></td><td class="sinBorde"></td>
	<td class="sinBorde" >
		<hr>FIRMA
	</td></tr>
</tbody>
</table>



</body>


<script type="text/javascript">
	function volver(){
		location = BASE_URL
	}
	$(document).ready(function(){
		window.print();
	});
</script>