
<form>
	<label for="nombre" class="form-control-label">NOMBRE:</label>
    <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Nombre de usuario">
    <br>


    <label for="correo" class="form-control-label">CORREO:</label>
    <input class="form-control" type="email" name="correo" id="correo" placeholder="Correo">
    <br>

    <label for="nombre_usuario" class="form-control-label">NOMBRE DE USUARIO:</label>
    <input class="form-control" type="text" name="nombre_usuario" id="nombre_usuario" placeholder="Nombre de usuario">
    <br>

	<label for="pass" class="form-control-label">CONTRASEÑA:</label>
    <input class="form-control" type="password" name="pass" id="pass" placeholder="contrasena">    
    <br>

    <label for="pass2" class="form-control-label">REPETIR CONTRASEÑA:</label>
    <input class="form-control" type="password" name="pass2" id="pass2" placeholder="contrasena">   

</form>