<div >
  <form>
  <label for="nombre" class="form-control-label">NOMBRE:</label>
    <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Nombre">
  <label for="correo" class="form-control-label">CORREO:</label>
    <input class="form-control" type="email" name="correo" id="correo" placeholder="Correo">
  <label for="rut" class="form-control-label">RUT:</label>
    <input class="form-control" type="text" name="rut" id="rut" placeholder="RUT">
  <label for="cargo" class="form-control-label">CARGO:</label>
    <input class="form-control" type="text" name="cargo" id="cargo" placeholder="Cargo" min="0">
  <label for="horas" class="form-control-label">HORAS DIARIAS:</label>
    <input class="form-control" type="time" name="horas" id="horas" placeholder="horas">

  </form>
</div>

<script type="text/javascript">
</script>