

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/plugins/wicket-master/wicket.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/plugins/wicket-master/wicket-gmap3.js"></script>


<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/plugins/wicket-master/wkt.js"></script>
<style type="text/css">
	#canvas {width:100%;height:300px;background:#AAA;border-left:1px solid #999;border-right:1px solid #999;}
	#wkt {width:100%;height:100px;border:1px solid #999;padding:3px;resize:none;}
	.controls {
  		margin-top: 10px;
  		border: 1px solid transparent;
  		border-radius: 2px 0 0 2px;
  		box-sizing: border-box;
        -moz-box-sizing: border-box;
  		height: 32px;
  		outline: none;
  		box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
}
	#pac-input {
 		background-color: #fff;
  		font-family: Roboto;
  		font-size: 15px;
  		font-weight: 300;
  		margin-left: 12px;
  		margin-bottom: 15px;
  		padding: 0 11px 0 13px;
  		text-overflow: ellipsis;
  		width: 300px;
	}
	#pac-input:focus {
  		border-color: #4d90fe;
	}
	.pac-container {
 		font-family: Roboto;
	}
	#type-selector {
  		color: #fff;
  		background-color: #4d90fe;
  		padding: 5px 11px 0px 11px;
	}

	#type-selector label {
  		font-family: Roboto;
  		font-size: 13px;
  		font-weight: 300;
	}
</style>


    
<div>
	<input type="text" class="form-control" name="imp_desc" id="imp_desc" value="" placeholder="Descripcion">
	<input id="pac-input" class="controls" type="text" placeholder="Buscar...">
  	<div id="canvas"></div>
    <textarea type="text" name="wkt" id="wkt" readonly></textarea>
    
</div>
        

<script type="text/javascript">
	
$( document ).ready(function() {
    console.log( "ready!" );
	app.gmap=app.initNew();	
});
	
	
</script>    



