<?php 
    $usuario = $this->usuario;
?>

<form>
	<label for="nombre" class="form-control-label">NOMBRE:</label>

    <input class="form-control" type="text" name="nombre" id="nombre" value="<?php echo $usuario[0]['nombre'] ?>">
    <input class="form-control" type="hidden" name="nombre_old" id="nombre_old" value="<?php echo $usuario[0]['nombre'] ?>">
    <br>

    <label for="correo" class="form-control-label">CORREO:</label>
    <input class="form-control" type="text" name="correo" id="correo" value="<?php echo $usuario[0]['correo'] ?>">
    <input class="form-control" type="hidden" name="correo_old" id="correo_old" value="<?php echo $usuario[0]['correo'] ?>">
    <br>

    <label for="nombre_usuario" class="form-control-label">NOMBRE DE USUARIO:</label>
    <input class="form-control" type="text" name="nombre_usuario" id="nombre_usuario" value="<?php echo $usuario[0]['usuario'] ?>">
    <input class="form-control" type="hidden" name="nombre_usuario_old" id="nombre_usuario_old" value="<?php echo $usuario[0]['usuario'] ?>">
    <br>

	<label for="pass" class="form-control-label">CONTRASEÑA: </label><small> dejar vacío para no cambiar contraseña</small>
    <input class="form-control" type="password" name="pass" id="pass" placeholder="contrasena">
    <input class="form-control" type="hidden" name="pass_old" id="pass_old" placeholder="contrasena">    
    <br>

    <label for="pass2" class="form-control-label">REPETIR CONTRASEÑA: </label><small> dejar vacío para no cambiar contraseña</small>
    <input class="form-control" type="password" name="pass2" id="pass2" placeholder="contrasena">   
    <input class="form-control" type="hidden" name="id" id="id" value="<?php echo $usuario[0]['id'] ?>">   


</form>