

<div id="footer" class="footerclass">
    <table align="center" class="textoB w80c">
        <tr>
            <td rowspan="2" align="left">
                <div class="logoB logo_footer alineado s24" onclick="window.open('http://www.t2b.cl', '_blank');"></div>
                <span class="alineado">Derechos Reservados &COPY; 2012<br/>Technology to Business Ltda.
                </span>
        </td>
            <td align="right"></td>
        </tr>
        <tr>
            <td align="right" >
                <span class="alineado"><a href="mailto:contacto.t2b@t2b.cl">contacto.t2b@t2b.cl</a></span><br/>
                <span class="alineado">Sistema probado en </span>
                <div class="img_brw brw_chrome" title="Chrome V.28 o superior"></div>
                <div class="img_brw brw_firefox" title="Firefox V.22 o superior"></div>
                <div class="img_brw brw_ie" title="Internet Explorer v.10 o superior"></div>
            </td>
        </tr>
    </table>
</div>

<?php global $menuItems; ?>