
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo My_ConfigIni::get('html')->titulo; ?></title>

   
  

        <!-- TITULO -->
        <title><?php echo My_ConfigIni::get('html')->titulo; ?></title>
        <!-- FAVICON -->
        <link rel="icon" href="<?php echo $this->baseUrl(); ?>/img/favicon.ico">
        <!-- BOOTSTRAP core CSS -->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">        
        <!-- FONT AWESOME -->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">

        <!-- CSS Calendar-->
              <!-- NProgress -->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/nprogress/nprogress.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/css/dataTables.bootstrap.css" rel="stylesheet"></script>
        <link href="<?php echo $this->baseUrl(); ?>/css/jquery.dataTables.min.css" rel="stylesheet"></script>
        <link href="<?php echo $this->baseUrl(); ?>/css/buttons.dataTables.1.2.4.min.css" rel="stylesheet"></script>

                <!-- iCheck Datatable-->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
                <!-- Datatables -->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
              <!-- FullCalendar -->
        <link href="<?php echo $this->baseUrl(); ?>/vendors/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet">
        <link href="<?php echo $this->baseUrl(); ?>/vendors/fullcalendar/dist/fullcalendar.print.css" rel="stylesheet" media="print">
          <!-- DatePicker Calendar -->      
        <link href="<?php echo $this->baseUrl(); ?>/vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet"> 
        <!-- CSS PROPIO -->
        <link href="<?php echo $this->baseUrl(); ?>/css/custom.css" rel="stylesheet">

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="" class="site_title"><i class="fa fa-empire" aria-hidden="true"></i> <span><?php echo My_ConfigIni::get('html')->titulo; ?></span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
             <!-- <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
              </div> -->
              <div class="profile_info">
                <span>Bienvenido,</span>
                <h2> <?php echo $this->session->username[0]["nombres"]  ?></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#" onclick="ir_menu(BASE_URL+'/index.php/index/vista');">Agregar/Editar tarea</a></li>
                      <li><a href="#" onclick="ir_menu(BASE_URL+'/index.php/index/calendar');">Calendario</a></li>
                      <li><a href="#" onclick="ir_menu(BASE_URL+'/index.php/index/tabla');">Dashboard3</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">

                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i> Administración <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#" onclick="ir_menu(BASE_URL+'/index.php/index/administrar-usuarios');">Administración de usuarios</a></li>
                      
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Configuración">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Pantalla completa">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Bloquear">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Cerrar sesión" onclick="cerrar_sesion();" >
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <h2 class=""><?php echo $this->session->username[0]["nombres"]." ".$this->session->username[0]["ape_paterno"] ?>                    <span class=" fa fa-angle-down"></span></h2>

                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Perfil</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Configuración</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Ayuda</a></li>
                    <li><a href='http://localhost/dashboard-ovas/public/index.php/index/logout';><i class="fa fa-sign-out pull-right"></i> Cerrar sesión</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                       <!-- <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span> -->
                        <span>
                          <span>Kevin Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>Kevin Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>Kevin Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>Kevin Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="" id="pagina_principal">
          <?php echo $this->layout()->content; ?>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            T2B - Technology to Business
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

      
        <!-- Base URL para usar con Javascript en vez de PHP -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/jquery/dist/jquery.min.js" type="text/javascript"></script>
         <!-- Bootstrap -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

        <script type="text/javascript"> const BASE_URL = "<?php echo $this->baseUrl(); ?>"; </script>
        <!-- Service 
        <script src="<?php echo $this->baseUrl(); ?>/js/service.js" type="text/javascript"></script>
             JS Menu 
        <script src="<?php echo $this->baseUrl(); ?>/js/menu.js" type="text/javascript"></script>
         App -->
        
        <!--utiljs con msg de carga-->
        <script src="<?php echo $this->baseUrl(); ?>/js/msgLoading.js" type="text/javascript"></script>

        <!-- Bootbox -->
        <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootbox.min.js" type="text/javascript"></script>
        <!-- Librerias DataTables -->
        <script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootbox.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery.dataTables.min_1.10.11.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/dataTables.buttons.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jszip.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/buttons.html5.min.js" type="text/javascript"></script>
        <!-- Librerias calendar -->
          <!-- jQuery -->
        
        <!-- FastClick -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/fastclick/lib/fastclick.js" type="text/javascript"></script>
        <!-- NProgress -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/nprogress/nprogress.js" type="text/javascript"></script>
        <!-- iCheck -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/iCheck/icheck.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/vendors/moment/min/moment.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/vendors/fullcalendar/dist/fullcalendar.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/vendors/fullcalendar/dist/locale-all.js" type="text/javascript"></script>
        <!-- JS Propio 
        <script src="<?php echo $this->baseUrl(); ?>/js/login.js"></script>-->
        <!-- Alertify -->
        <script src="https://cdn.rawgit.com/alertifyjs/alertify.js/v1.0.10/dist/js/alertify.js"></script>
                <!--BLOCK UI-->
        <script src="<?php echo $this->baseUrl(); ?>/plugins/blockUI/jquery.blockUI.js"></script>
                <!-- DATE TIME PICKER CALENDAR -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/app.js" type="text/javascript"></script>
        <!-- Datatables -->
        <script src="<?php echo $this->baseUrl(); ?>/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
        


        <script type="text/javascript">
        





         function cerrar_sesion() {

          // confirm dialog
            alertify.confirm("Está seguro que desea cerrar sesión?", function () {
            // window.location("http://localhost/dashboard-ovas/public/index.php/index/logout");
             location.href=BASE_URL+'/index.php/index/logout';

          }, function() {
              // user clicked "cancel"
                     alertify.error("Se canceló cierre sesión");
          });
         }

        $(document)
          .ajaxStart(function () {
           esperaON();
          })
          .ajaxStop(function () {
           esperaOFF();
          });

        </script>
  </body>
</html>