<li><a href="#"><i class='fa fa-gear'></i> <span>Configuraciones Core</span></a></li>
<li><a href="#"><i class='fa fa-volume-up'></i> <span>Core Voz</span></a>
    
</li>

<li class="treeview">
    <a href="#"><i class='fa fa-globe'></i> <span>Core Internacional</span><i class="fa fa-angle-right pull-right"></i></a>
    <ul class="treeview-menu">
        <li><a href="#">Link in level 2</a></li>
        <li>
            <a href="#">Link in level 2 <i class="fa fa-angle-right pull-right"></i></a>
            <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
            </ul>
        </li>
    </ul>
</li>